print("hello\"Ayush\" world")
print("line A")
print("line B")
print("line A\nline B")
print("Name\tAyush")
print("this is backlash\\")
print("this is double backlash\\\\")
print("hell\blo")
print(r"line A \n line B")